server:
  port: 8310
spring:
  application:
    name: single-user-service


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/single_application?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8300/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10



mybatis:
  type-aliases-package: com.gbicc.entity